name: Trigger auto deployment for first-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/first-container-app-AutoDeployTrigger-69c9f540-68f8-4ed3-bc3a-a4a7031fdb73.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: firstcontainerregistry11.azurecr.io
          username: ${{ secrets.FIRSTCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.FIRSTCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: firstcontainerregistry11.azurecr.io/first-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FIRSTCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n first-container-app -g spring-service --server firstcontainerregistry11.azurecr.io --username  ${{ secrets.FIRSTCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.FIRSTCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n first-container-app -g spring-service --image firstcontainerregistry11.azurecr.io/first-container-app:${{ github.sha }}
